version: '3.4'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_ADDR: db
      DB_VENDOR: mysql
      DB_DATABASE: keycloak
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: keycloak_mysql
    restart: always
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root

